### ISSUE TITLE
can not use iopay?

### ISSUE THREAD

**Issue by huangmeibao** [iotexproject/iotex-dapp-sample#1]
hi 

This demo can not use iopay wallet for connection? I don't see the corresponding choice

**Comment by uu-z** [comment]
> hi
> 
> This demo can not use iopay wallet for connection? I don't see the corresponding choice

yes, for some reason we only support web3 protocol wallet on this demo. For experimental iopay support you could refer here. (not finish yet)
https://github.com/uu-z/vite-react-mobx/blob/dapp/src/store/lib/IotexNetworkState.ts
https://github.com/uu-z/vite-react-mobx/blob/dapp/src/components/IotexProvider/index.tsx
