### ISSUE TITLE
how to use cheact sheet in the code?

### ISSUE THREAD

**Issue by NabiiBux** [iotexproject/iotex-dapp-sample#48]
hello, I am struggling to create dapp , please guide me , how to use cheat sheet? 
Thanks

**Comment by uu-z** [comment]
> hello, I am struggling to create dapp , please guide me , how to use cheat sheet? Thanks

hi @NabiiBux  the cheat sheet in readme is currently part of the V2 version, you can refer to this branch which contains an example
https://github.com/iotexproject/iotex-dapp-sample/tree/v2

**Comment by uu-z** [comment]
The new V3 version is still in the works, the examples and documentation will be released later

**Comment by NabiiBux** [comment]
> > hello, I am struggling to create dapp , please guide me , how to use cheat sheet? Thanks
> 
> hi @NabiiBux the cheat sheet in readme is currently part of the V2 version, you can refer to this branch which contains an example https://github.com/iotexproject/iotex-dapp-sample/tree/v2

do you have an idea how create marketplace for nfts selling ,purchasing and staking using iotex network , i already deployed contract using Xrc721 , minted nft collection , for reselling of artwork , i need that kind of boilerplate can you provide or help me in this regard , your help serve me the best . Thank you , awaiting for your reply
