### ISSUE TITLE
there is a dev error, anyone can help me? 

### ISSUE THREAD

**Issue by Joycessh** [iotexproject/iotex-dapp-sample#49]
yarn run v1.22.18projects\funny>yarn dev
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
(node:18132) ExperimentalWarning: The ESM module loader is experimental.
wait  - compiling...
warn  - ./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/nexus/dist-esm/typegenFormatPrettier.js
Module not found: Can't resolve 'prettier' in 'D:\workspaces\my-projects\funny\node_modules\nexus\dist-esm'

./node_modules/nexus/dist-esm/utils.js
Critical dependency: the request of a dependency is an expression
warn  - ./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/nexus/dist-esm/typegenFormatPrettier.js
Module not found: Can't resolve 'prettier' in 'D:\workspaces\my-projects\funny\node_modules\nexus\dist-esm'

./node_modules/nexus/dist-esm/utils.js
Critical dependency: the request of a dependency is an expression
wait  - compiling /404 (client and server)...
wait  - compiling...
warn  - ./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/nexus/dist-esm/typegenFormatPrettier.js
Module not found: Can't resolve 'prettier' in 'D:\workspaces\my-projects\funny\node_modules\nexus\dist-esm'

./node_modules/nexus/dist-esm/utils.js
Critical dependency: the request of a dependency is an expression
warn  - ./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/nexus/dist-esm/typegenFormatPrettier.js
Module not found: Can't resolve 'prettier' in 'D:\workspaces\my-projects\funny\node_modules\nexus\dist-esm'

./node_modules/nexus/dist-esm/utils.js
Critical dependency: the request of a dependency is an expression
wait  - compiling / (client and server)...
wait  - compiling...
warn  - ./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/nexus/dist-esm/typegenFormatPrettier.js
Module not found: Can't resolve 'prettier' in 'D:\workspaces\my-projects\funny\node_modules\nexus\dist-esm'

./node_modules/nexus/dist-esm/utils.js
Critical dependency: the request of a dependency is an expression
warn  - ./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/nexus/dist-esm/typegenFormatPrettier.js
Module not found: Can't resolve 'prettier' in 'D:\workspaces\my-projects\funny\node_modules\nexus\dist-esm'

./node_modules/nexus/dist-esm/utils.js
Critical dependency: the request of a dependency is an expression
wait  - compiling /500 (client and server)...
wait  - compiling...
warn  - ./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/nexus/dist-esm/typegenAutoConfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/nexus/dist-esm/typegenFormatPrettier.js
Module not found: Can't resolve 'prettier' in 'D:\workspaces\my-projects\funny\node_modules\nexus\dist-esm'

./node_modules/nexus/dist-esm/utils.js
Critical dependency: the request of a dependency is an expression
error - SyntaxError: The requested module 'bech32' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'bech32';
const {bech32} = pkg;

**Comment by uu-z** [comment]
Could you please try again using `pnpm`?

**Comment by Joycessh** [comment]
thank you pnpm resolves this problem.

**Comment by Joycessh** [comment]
the Dapp Connects on TokenPocket, it works not good, Unable to adapt to mobile.
